### ISSUE TITLE
Bullseye error

### ISSUE THREAD

**Issue by danfossi** [thctlo/Kopano#12]
Something is not working properly on Debian 11, after a fresh install by running the script it stuck here:

```
Script is running on : Debian bullseye
curl found
jq found
apt-ftparchive found
Script is missing a needed program/package: gnupg, installing now : Detected variable REPO_BASE_FOLDER/GET_ARCH : /srv/repo/kopano/amd64/
NOT Detected : /srv/repo/kopano/amd64/ creating folder now.
Please wait, getting kopano components : core : #
```

**Comment by thctlo** [comment]
Hai, not its more that i already builded in support for bullseye, but there kopano hasnt release the bullseye release yet. 
:-( im waiting on that one also. 

I'll add some better visable text that ist not ready yet.

**Comment by thctlo** [comment]
that is correct, there no kopano debian 11 packages yet. Op 5 feb. 2022 11:36 schreef Dennis ***@***.***>:
Something is not working properly on Debian 11, after a fresh install by running the script it stuck here:
Script is running on : Debian bullseye
curl found
jq found
apt-ftparchive found
Script is missing a needed program/package: gnupg, installing now : Detected variable REPO_BASE_FOLDER/GET_ARCH : /srv/repo/kopano/amd64/
NOT Detected : /srv/repo/kopano/amd64/ creating folder now.
Please wait, getting kopano components : core : #
