### ISSUE TITLE
kopano webapp not being installed

### ISSUE THREAD

**Issue by ThomasHaase** [thctlo/Kopano#14]
Hello everyone.
By reading the default configuration, it should also install the kopano webapp:
`KOPANO_COMMUNITY_PKG="core archiver files mdm smime webapp migration-pst"`
After installation (apt install kopano-server-packages) I wondered why the web interface isn't available.
Server etc. everything is running.

By simulation a remove of kopano-server-package I noticed that the webapp wasn't installed.
Is there a way to check if there was an error during installation?
```
catdoc kopano-backup kopano-client kopano-common kopano-dagent kopano-dagent-pytils kopano-gateway kopano-ical kopano-lang kopano-monitor kopano-python-utils kopano-search
  kopano-server kopano-spooler libgsoap-kopano-2.8.109 libhx28 libjsoncpp1 libkcarchiver0 libkcfreebusy0 libkcicalmapi0 libkcinetmapi0 libkcoidc0 libkcpyplug0 libkcserver0
  libkcsoap0 libkcutil0 libmapi1 libmariadb3 libs3-4 libtcmalloc-minimal4 libvmime-kopano3 mariadb-common python3-bsddb3 python3-daemon python3-dateutil python3-kopano
  python3-kopano-search python3-kopano-utils python3-lockfile python3-mapi python3-tz python3-tzlocal python3-xapian xsltproc
```
```
apt-cache policy kopano-server-packages kopano-webapp z-push-kopano
kopano-server-packages:
  Installiert:           11.0.2.51.76cf85b89-0+877.1
  Installationskandidat: 11.0.2.51.76cf85b89-0+877.1
  Versionstabelle:
 *** 11.0.2.51.76cf85b89-0+877.1 500
        500 file:/srv/repo/kopano amd64/ Packages
        100 /var/lib/dpkg/status
kopano-webapp:
  Installiert:           (keine)
  Installationskandidat: 6.0.0.66-1+2030.1
  Versionstabelle:
     6.0.0.66-1+2030.1 500
        500 file:/srv/repo/kopano amd64/ Packages
z-push-kopano:
  Installiert:           (keine)
  Installationskandidat: 2.6.4+0-0
  Versionstabelle:
     2.6.4+0-0 500
        500 https://download.kopano.io/zhub/z-push:/final/Ubuntu_20.04  Packages
```
It seems that I can install it by 
`apt install kopano-webapp`
Version 6.0.0.66 is the latest one.

Edit: also migration-pst isn't installed, but should by default.

Using Linux Mint with Ubuntu 20.04

**Comment by thctlo** [comment]
it looks like the webapp and z-push are not in the package kopano-server-packages anymore or the name of the packages changed a bit.  

I'll add them  in the script, thanks for reporting it. Most welkom.

**Comment by ThomasHaase** [comment]
THank you. I just manually installed the missing packages and it works. Thank you for this corrective action.
