### ISSUE TITLE
issue running

### ISSUE THREAD

**Issue by killmasta93** [thctlo/Kopano#2]
hi,
trying to run the script but getting this error

      Getting and extracting : files ( -amd64 ) 
          curl: (3) <url> malformed

            gzip: stdin: unexpected end of file
           tar: Child returned status 1
            tar: Error is not recoverable: exiting now

**Comment by NetSpider-AT** [comment]
hi have the same issue and solved by editing the script. 
Modify the line 146

from:
if [ "${pkglist}" = "mdm" ]||[ "${pkglist}" = "webapp" ]
to:
if [ "${pkglist}" = "mdm" ]||[ "${pkglist}" = "webapp" ]||[ "${pkglist}" = "files" ]

the file section is not listed for every architecture instead there is an “all” package

**Comment by killmasta93** [comment]
Thanks for the reply, that did the trick but got this error after i ran apt-get update

```
Reading package lists... Done
N: Can't drop privileges for downloading as file '/root/kopano-repo/apt/amd64/InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
W: GPG error: https://repo.z-hub.io/z-push:/final/Ubuntu_16.04  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5CB27E1358E2F2A7
W: The repository 'http://repo.z-hub.io/z-push:/final/Ubuntu_16.04  Release' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

if I understood correctly after running the script i need to then run 

```
apt install kopano-server-packages
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package kopano-server-packages

```

**Comment by thctlo** [comment]
Hai guys, first of all Happy New Year,
I changed the script, uploading it in few minutes,

**Comment by thctlo** [comment]
Uploaded, if one can verify it on ubuntu.

**Comment by NetSpider-AT** [comment]
Hi, 

it stall by 
Getting and extracting : dependencies ( -amd64 ) 
Downloading files to downloads folder : dependencies  ( -amd64 )
curl: (3) <url> malformed

for this package are no files in the repository for Unbuntu, only Debian 10

**Comment by thctlo** [comment]
Thank for the checkup. 
It's fixed now, im closing the report.
