### ISSUE TITLE
N: Download is performed unsandboxed as root as file .......

### ISSUE THREAD

**Issue by ckruijntjens** [thctlo/Kopano#6]
Hi,

I downloaded your script. works perfect thank you for the effort of creating this! However i am getting a warning message when i do a apt update on my debian buster system.

this is the warning message:

`All packages are up to date.
N: Download is performed unsandboxed as root as file '/root/kopano-repo/apt/amd64/InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
root@mail:~# N: Download is performed unsandboxed as root as file`

Any idea how i can resolve this?

**Comment by vizonyc** [comment]
Having the same issue would love to resolve this one.

**Comment by thctlo** [comment]
well, you can fix that my setting the location to for example  your personal homedir. 
(dont forget to change the apt file then) 

But you can ignore that warning, its not something to worry about.

**Comment by thctlo** [comment]
Hai, i've updated the script, you should not see these messages again now. 
If you guys can try it and let me know the results.

**Comment by thctlo** [comment]
closing this one, its fixed.

**Comment by panayotovip** [comment]
i do have this problem too.
N: Download is performed unsandboxed as root as file '/home/USER/Downloads/zoom_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

**Comment by ckruijntjens** [comment]
Kopano is deadVriendelijke groet,Chris Kruijntjens.Van: Ivan Panayotov ***@***.***> verzonden: maandag 26 juni 2023 21:53 Aan: thctlo/Kopano Cc: ckruijntjens; AuthorOnderwerp: Re: [thctlo/Kopano] N: Download is performed unsandboxed as root as file ....... (#6)
i do have this problem too.
N: Download is performed unsandboxed as root as file '/home/USER/Downloads/zoom_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/thctlo/Kopano/issues/6#issuecomment-1608139951",
"url": "https://github.com/thctlo/Kopano/issues/6#issuecomment-1608139951",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
